repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        # https://github.com/psf/black/issues/395
        exclude: "./*.ipynb"
      - id: check-yaml
      - id: check-added-large-files
        # https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repo_pre_commit_hooks/check-added-large-files/check-added-large-files.html#check-added-large-files-prevent-giant-files-from-being-committed
        args: ["--maxkb=900"]
      - id: check-ast
      - id: check-json
        exclude: (.devcontainer/*.json|.vscode/launch.json)
        # https://gitlab.idiap.ch/beat/beat.core/blob/master/.pre-commit-config.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell README.md src/* tests/*
        language: python
        types: [text]
        exclude: "./*.ipynb"
